### ISSUE TITLE
Demo中的右边那幅相机运动示意图是怎么做出来的呀？

### ISSUE THREAD

**Issue by williamtang** [vshawn/Shawn_pose_estimation_by_opencv#1]
你好，看到你博客上的那个演示视频，比较好奇右边那个示意图是怎么做的呀？是利用什么工具吗？

是用的LabView？

**Comment by VShawn** [comment]
是的，labview做的，用的三维图片控件，相关代码我放在
https://github.com/vshawn/Shawn_pose_estimation_by_opencv/tree/master/用LabView重建相机位置
