### ISSUE TITLE
关于solvepnp得到的旋转矩阵问题

### ISSUE THREAD

**Issue by jyl58** [vshawn/Shawn_pose_estimation_by_opencv#3]
看了您的博客，学到很多东西。有个问题想请教一下：
这个Shawn_pose_estimation_by_opencv/include/PNPSolver.cpp文件中 Solve函数中调用完solvepnp后提取
的旋转矩阵RoteM（86行） 是哪个坐标系到哪个坐标系的旋转矩阵？世界系到相机系，还是相机系到世界系？

**Comment by VShawn** [comment]
//忙着办理入职，很久没上过GIT了
这个问题目前没有明晰，引用我与他人的邮件讨论：

> 官方文档确实说计算出的旋转向量、平移向量是从世界系到相机系。但在实际论证过程中，我遇到了问题，按照官方给出的说法，将旋转向量换算为旋转矩阵，进一步解出欧拉角后，我发现无法根据这些旋转角度将相机转正。反而，如果将该向量理解为从相机系到世界系时，却得到了正确的解。

> 我本身是搞图像反馈控制的，这个方向只是兴趣使然，对这一块的数学问题其实并不很了解，但根据我的猜测有两个可能：

> 1.旋转向量在转换为旋转矩阵时，其指向性发生了变化？（变为从相机系到世界系）我数学功底不好，对这一点无法论证。

> 2.旋转结果与旋转的次序有关，是否在实践时我弄反了三个轴的旋转次序？这一点文档中并未给出旋转次序，因此我也没论证到底是不是这里存在问题。
